name: 'Validate Product Version'
description: 'Check that product version output includes expected version string'
inputs:
  expected_version:
    type: string
    description: 'Expected version string'
    required: true
  artifact_path:
    type: string
    description: "Path to artifacts to test"
    required: true
  soft_fail:
    type: string
    # this input should only be set by CRT workflows or internal tests
    description: 'If non-empty, lack of support is not a fatal error'

runs:
  using: "composite"
  steps:

    - name: Check Product Support
      id: check-product-support
      shell: bash
      env:
        # Let the support checker know where to find the supported builds data
        SUPPORT_JSON: "${{ github.action_path }}/supported_builds.json"
      run: |
        tool="${{ inputs.artifact_path }}"
        tool="${tool##*/}"
        supported="$(${{ github.action_path }}/check-product-support "${{ inputs.artifact_path }}")"
        echo "supported=$supported" > "$GITHUB_OUTPUT"

        if [ "$supported" != 'true' ] ; then
          echo "Tool is not supported by this action." 1>&2
          [ -n "${{ inputs.soft_fail }}" ] && exit 0 # exit 1 if soft_fail unset
        fi

    - name: Check Artifact
      if: steps.check-product-support.outputs.supported == 'true'
      shell: bash
      env:
        TEST_DIR: "${{ runner.temp }}/validate-product-version"
        EXP_VERSION: "${{ inputs.expected_version }}"
      run: |
        echo "::group::setup"
        echo "testing ${{ inputs.artifact_path }}"
        case "${{ inputs.artifact_path }}" in
          /*) ARTIFACT="${{ inputs.artifact_path }}" ;; # absolute path used as-is
          *)  ARTIFACT="$(pwd -P)/${{ inputs.artifact_path }}" ;;
        esac
        export ARTIFACT
        echo "ARTIFACT=$ARTIFACT"

        if ! [ -e "$ARTIFACT" ]; then
          echo "::error $ARTIFACT: artifact path does not exist"
          exit 1
        fi

        mkdir -p "$TEST_DIR"
        cd "$TEST_DIR"
        echo "::endgroup::"
        "${{ github.action_path }}/test-versions"
