
name: CI Tests
on:
  push:

permissions:
  contents: read

env:
  BATS_TAG: v1.9.0
  # We use this commit to verify that the tag hasn't been moved.
  BATS_COMMIT: 6636e2c2ef5ffe361535cb45fc61682c5ef46b71
  BATS_REPO: https://github.com/bats-core/bats-core.git

jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Install BATS
        run: |
          cd ../
          git clone --depth 1 --branch "$BATS_TAG" --single-branch "$BATS_REPO"
          cd bats-core/bin
          GOT_COMMIT="$(git rev-parse HEAD)"
          if [ "$GOT_COMMIT" -ne "$BATS_COMMIT" ]; then
            echo "==> FATAL: BATS tag $BATS_TAG has been moved; got ${GOT_TAG:(0:8)}; want ${BATS_TAG:(0:8)}"
            echo "==> DO NOT JUST UPDATE THE BATS_COMMIT VARIABLE, FIRST CHECK THAT THE REPO HAS NOT BEEN COMPROMISED"
            exit 1
          fi
          echo "$PWD" >> "$GITHUB_PATH"

      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Run Test Suite
        run: bats ./tests/test-versions.bats

  test-relative:
    runs-on: ubuntu-latest
    needs: [ 'test-suite' ]
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      # Test with relative path
      - name: Run Action (relative path)
        uses: hashicorp/actions-validate-product-version@v1
        with:
          expected_version: '1.2.3'
          # this path is relative to the action path
          artifact_path: ./tests/testdata/test_tool_plain_executable

  test-absolute:
    runs-on: ubuntu-latest
    needs: [ 'test-suite' ]
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      # Test with absolute path
      - name: Copy Test Tool to Absolute Path
        id: copy_tool
        run: |
          cp ./tests/testdata/test_tool_plain_executable "${{ runner.temp }}/test_tool_plain_executable"
      - name: Run Action (absolute path)
        uses: hashicorp/actions-validate-product-version@v1
        with:
          expected_version: '1.2.3'
          # this path is relative to the action path
          artifact_path: ${{ runner.temp }}/test_tool_plain_executable
